<?php
//Global define
DEFINE('BASE_URL', 'http://vimolia.local/');
DEFINE('BASE_URL_ADMIN', 'http://vimolia.local/admin/');
DEFINE('APP_TITLE', 'VIMOLIA');
DEFINE('APP_VERSION', '');
DEFINE('LOG_DIRECTORY', DIRECTORY_SEPARATOR.'logs'.DIRECTORY_SEPARATOR);
DEFINE('WEBMASTER_ADDRESS', '');
//DB define
DEFINE('USING_A_DB', TRUE); //SET TO TRUE IF YOU USE A DB WITH THE FOLLOWING INFO
DEFINE('DBNAME', 'D2M_BDD');
DEFINE('DBHOST', 'localhost');
DEFINE('DBTYPE', 'mysql');
DEFINE('DBPORT', '3306');
DEFINE('DBUSER', 'D2M_USER');
DEFINE('DBPASSWORD', 'D2M_MDP_$');
//EMAIL INFO
DEFINE('EMAIL_FROM', 'vimolia.esgi@gmail.com');
DEFINE('EMAIL_FROM_NAME', 'Vimolia');
DEFINE('EMAIL_REPLY', EMAIL_FROM);
DEFINE('EMAIL_REPLY_NAME', 'Vimolia');
DEFINE('EMAIL_SMTP_HOST', 'smtp.gmail.com');
DEFINE('EMAIL_SMTP_ADDRESS', EMAIL_FROM);
DEFINE('EMAIL_SMTP_PWD', '6tFh3zV8');
DEFINE('EMAIL_SMTP_PORT', 465);

?>