<?php
//Global define
DEFINE('BASE_URL', 'http://vimolia.local/');
DEFINE('APP_TITLE', '');
DEFINE('APP_VERSION', '');
DEFINE('LOG_DIRECTORY', DIRECTORY_SEPARATOR.'logs'.DIRECTORY_SEPARATOR);
DEFINE('WEBMASTER_ADDRESS', '');
//DB define
DEFINE('USING_A_DB', TRUE); //SET TO TRUE IF YOU USE A DB WITH THE FOLLOWING INFO
DEFINE('DBNAME', 'D2M_BDD');
DEFINE('DBHOST', 'localhost');
DEFINE('DBTYPE', 'mysql');
DEFINE('DBPORT', '3306');
DEFINE('DBUSER', 'D2M_USER');
DEFINE('DBPASSWORD', 'D2M_MDP_$');

?>